import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),modules=process.env.DIDBAN_TEST_MODULES||path.join(here,'node_modules');
const {chromium}=await import(pathToFileURL(path.join(modules,'playwright/index.mjs')));
const {default:AxeBuilder}=await import(pathToFileURL(path.join(modules,'@axe-core/playwright/dist/index.mjs')));
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'didban-form-'));
const browser=await chromium.launch({headless:true,...(process.env.DIDBAN_CHROMIUM_PATH?{executablePath:process.env.DIDBAN_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.DIDBAN_TEST_URL||pathToFileURL(path.join(here,'../docs/index.html')).href);
 const login=async role=>{if(await page.locator('[data-action=logout]').count())await page.locator('[data-action=logout]').click();await page.locator(`[data-action=login-group][data-id="${role}"]`).click();await page.locator('#login-form button[type=submit]').click()};
 await login('consultant');await page.locator('.nav [data-id=programs]').click();
 for(const location of ['بلوک الف — محل آزمون','بلوک ب — محل آزمون']){
  await page.locator('[data-action=assign-mandatory-point][data-id=PR-1]').click();assert.equal(await page.locator('#modal-form [name=sourceCode] option[value="6-1-3-1"]').count(),0);await page.locator('#modal-form [name=sourceCode]').selectOption('4-4-1');await page.locator('#modal-form [name=location]').fill(location);if(location.startsWith('بلوک ب'))await page.screenshot({path:path.join(dir,'consultant-mandatory-referral.png')});await page.locator('#modal-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);
 }
 await login('inspector');await page.locator('[data-action=start-inspector-report][data-id=PR-1]').click();assert.equal(await page.locator('#modal-form input[type=radio][value=C]').count(),2);assert.equal(await page.locator('#modal-form [name=phase]').count(),0);
 const id=await page.evaluate(()=>selectedReport);const title=await page.evaluate(()=>SOURCE_ITEMS.find(x=>x.code==='4-4-2').title);assert.equal(await page.locator('#modal-form [name=additionalChecklistCode] option[value="4-4-2"]').textContent(),'۴-۴-۲ — '+title);assert.equal(await page.locator('#modal-form [name=additionalChecklistCode] option[value="4-3"]').count(),0);assert.equal(await page.locator('#modal-form [name=additionalChecklistCode] option[value="6-1-3-1"]').count(),0);
 await page.locator('#modal-form [name=observation0]').fill('گزارش آزمایشی درباره همان نقطه ارجاع مشاور');await page.locator('#modal-form [name=code0][value=NC-M]').check();await page.locator('#modal-form [name=rowDocuments0]').setInputFiles({name:'تصویر آزمایشی.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl9sAAAAASUVORK5CYII=','base64')});
 await page.locator('#modal-form [name=additionalChecklistCode]').selectOption('4-4-2');await page.locator('[data-action=add-checklist-item]').click();await page.waitForFunction(()=>document.querySelector('#modal-form [name=observation2]'));
 assert.equal(await page.locator('#modal-form [name=observation0]').inputValue(),'گزارش آزمایشی درباره همان نقطه ارجاع مشاور');assert.equal(await page.locator('#modal-form .checklist-photos img').count(),1);await page.locator('#modal-form .checklist-photos img').evaluate(img=>img.scrollIntoView());await page.waitForFunction(()=>document.querySelector('#modal-form .checklist-photos img')?.naturalWidth>0);assert.equal(await page.locator('#modal-form [name=code0]:checked').inputValue(),'NC-M');
 await page.locator('#modal-form [name=observation2]').fill('گزارش بند دیگری که بازرس از چک‌لیست فراخوانی کرد');await page.locator('#modal-form [name=inspectorAnalysis2]').fill('تحلیل بازرس بر پایه مشاهده و مستند');await page.locator('#modal-form [name=additionalChecklistCode]').evaluate(el=>el.closest('section').scrollIntoView({block:'start'}));await page.screenshot({path:path.join(dir,'inspector-checklist-dropdown.png')});
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(x=>({id:x.id,targets:x.nodes.map(n=>n.target)})),[]);
 await page.locator('#modal-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('[data-action=report-scope]').click();await page.locator('#modal-form [name=codes]').selectOption([]);await page.locator('#modal-form [name=reason]').fill('خارج کردن بند بازرس؛ نقاط مشاور باید باقی بمانند');await page.locator('#modal-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);
 const saved=await page.evaluate(id=>{const r=engine.reports().find(x=>x.id===id);return {rows:r.rows.map(x=>({id:x.id,point:x.mandatoryPointId})),doc:r.documents[0],excluded:r.excludedRows.length}},id);assert.equal(saved.rows.length,2);assert.ok(saved.rows.every(x=>x.point));assert.equal(saved.doc.rowId,saved.rows[0].id);assert.equal(saved.doc.sourceCode,'4-4-1');assert.equal(saved.doc.by,'inspector');assert.equal(saved.excluded,1);
 await page.reload();assert.equal(await page.evaluate(id=>engine.db.inspectionReports.find(x=>x.id===id).documents[0].rowId,id),saved.rows[0].id);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=390));assert.deepEqual(errors,[]);
 console.log('PASS: consultant source-only dropdown referral, two mandatory locations, inspector source-only additional clause, photo bound to its clause, draft retained while adding, mandatory preservation, reload, mobile and axe.');console.log('Artifacts: '+dir);
}finally{await browser.close()}
