/* New source screens, offline forms, scope, printing and presentation artifact. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const modules=process.env.DIDBAN_TEST_MODULES||path.join(here,'node_modules');
const {chromium}=await import(pathToFileURL(path.join(modules,'playwright/index.mjs')));
const {default:AxeBuilder}=await import(pathToFileURL(path.join(modules,'@axe-core/playwright/dist/index.mjs')));
const browser=await chromium.launch({headless:true,...(process.env.DIDBAN_CHROMIUM_PATH?{executablePath:process.env.DIDBAN_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'didban-source-'));
try {
 const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce',acceptDownloads:true});
 const page=await context.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 await page.goto(pathToFileURL(path.join(here,'../docs/index.html')).href);
 const login=async(user,v)=>page.evaluate(({user,v})=>{engine.login(user,'demo123');view=v;selectedReport=null;render()},{user,v});
 const a11y=async name=>{const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(x=>({id:x.id,targets:x.nodes.map(n=>n.target)})),[],name)};
 await login('consultant','source-projects');assert.equal(await page.locator('tbody tr').count(),69);await a11y('source registry');
 await page.locator('#source-search input').fill('افتخار رویان');await page.locator('#source-search button').click();assert.equal(await page.locator('tbody tr').count(),1);
 await page.locator('[data-action=source-demo][data-id="SRC-C03-010"]').click();
 await page.locator('#modal-form button[type=submit]').click();
 await page.waitForSelector('.source-report');
 assert.match(await page.locator('.source-report').innerText(),/۴۷٫۵۱|۴۷.۵۱/);
 assert.match(await page.locator('.source-report').innerText(),/قابل محاسبه نیست/);
 assert.match(await page.locator('.source-report').innerText(),/ساختگی/);
 await a11y('source report');
 const reportId=await page.evaluate(()=>selectedReport);
 await page.screenshot({path:path.join(dir,'source-report-full.png'),fullPage:true});
 await page.screenshot({path:path.join(dir,'source-report-preview.png')});
 await page.emulateMedia({media:'print'});await page.pdf({path:path.join(dir,'source-report.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
 await page.locator('[data-action=nav][data-id=source-reference]').click();await a11y('source reference');
 await page.locator('#source-item-search [name=itemQuery]').fill('۶-۱-۳-۱۰');await page.locator('#source-item-search button').click();
 assert.equal(await page.locator('#source-catalogue tbody tr').count(),1);assert.match(await page.locator('#source-catalogue').innerText(),/ماشین لباسشویی/);
 await page.locator('#source-item-search [name=itemQuery]').fill('10-7-10');await page.locator('#source-item-search button').click();assert.match(await page.locator('#source-catalogue').innerText(),/عبارت ناقص/);
 await page.locator('#source-item-search [name=itemQuery]').fill('5-6-4-8');await page.locator('#source-item-search button').click();assert.match(await page.locator('#source-catalogue').innerText(),/والد اعلامی/);
 await page.locator('#source-item-search [name=itemQuery]').fill('6-1-3');await page.locator('#source-item-search button').click();
 await page.locator('#source-catalogue').screenshot({path:path.join(dir,'source-checklist-preview.png')});
 await page.locator('[data-action=source-classify]').click();
 for(const [name,value]of Object.entries({blocks:'4',floors:'6',area:'8000'}))await page.locator(`#modal-form [name=${name}]`).fill(value);
 for(const name of ['quality','qms','experience','pastQuality'])await page.locator(`#modal-form [name=${name}]`).selectOption('3');
 await page.locator('#modal-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#modal-title')?.textContent.includes('نتیجه'));
 assert.match(await page.locator('#modal').innerText(),/گروه نظارت ۲/);await page.locator('#modal-form button[type=submit]').click();
 await login('inspector','reports');await page.locator(`[data-action=open-report][data-id="${reportId}"]`).click();await page.locator('[data-action=edit-report]').click();
 assert.equal(await page.locator('#modal-form select[name=level0]').inputValue(),'0.75');
 await page.locator('#modal-form select[name=level0]').selectOption('0');await page.locator('#modal-form [name=observation0]').fill('مشاهده ساختگی ویرایش‌شده برای آزمون');
 await page.locator('#modal-form [name=submit]').check();await page.locator('#modal-form button[type=submit]').click();
 await page.waitForFunction(()=>!document.querySelector('#modal').open);
 assert.equal(await page.locator('[data-action=edit-report]').count(),0);
 assert.equal(await page.evaluate(id=>engine.reports().find(r=>r.id===id).rows[0].assessmentLevel,reportId),0);
 await login('inspector3','reports');
 const archId=await page.evaluate(()=>engine.reports().find(r=>r.schemaVersion===3).id);
 await page.locator(`[data-action=open-report][data-id="${archId}"]`).click();assert.match(await page.locator('.source-plan').innerText(),/دیوارچینی/);
 await page.locator('[data-action=edit-report]').click();await page.locator('#modal-form summary').filter({hasText:'ماتریس فعالیت‌های اجباری منبع'}).click();
 for(const [name,value]of Object.entries({pointTotal0:'2',pointVisited0:'1',pointUnit0:'دیوار',pointLocations0:'بلوک فرضی',pointReason0:'دسترسی فرضی محدود',pointRevisit0:'بازدید تکمیلی فرضی',pointEvidence0:'شاهد ساختگی'}))await page.locator(`#modal-form [name=${name}]`).fill(value);
 await page.locator('#modal-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);
 assert.equal(await page.evaluate(id=>engine.reports().find(r=>r.id===id).mandatoryPoints[0].visited,archId),1);
 assert.match(await page.locator('.source-plan').innerText(),/تعیین نشده/);await a11y('source mandatory plan');
 await page.reload();await login('c03','reports');assert.equal(await page.locator(`[data-action=open-report][data-id="${reportId}"]`).count(),1);
 await page.locator(`[data-action=open-report][data-id="${reportId}"]`).click();assert.equal(await page.locator('[data-action=edit-report]').count(),0);
 const download=page.waitForEvent('download');await page.locator('[data-action=export-report]').click();const dl=await download;await dl.saveAs(path.join(dir,'source-report.json'));
 const report=JSON.parse(await fs.readFile(path.join(dir,'source-report.json'),'utf8'));assert.equal(report.progress.plannedProgress,null);assert.equal(report.status,'Submitted');assert.equal(report.subsidiary,'C03');assert.equal(report.schemaVersion,3);assert.equal(report.history.length,1);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=390));await a11y('mobile source report');await page.screenshot({path:path.join(dir,'source-mobile.png'),fullPage:true});
 await login('c10','reports');assert.equal(await page.locator(`[data-action=open-report][data-id="${reportId}"]`).count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 console.log('PASS: source registry, filtering, four-report scenario, calculator, scoring, submit, role scope, persistence, JSON, print, mobile and axe.');console.log('Artifacts: '+dir);
} finally {await browser.close()}
